baseURL: https://slowlang.github.io/blog/
languageCode: en-us
title: Slow Progress Blog
theme: PaperMod
googleAnalytics: G-PVB527HBWT

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Slow Blog
  description: "Slow lang development blog"
  keywords: [Blog, Slowlang, slow, "programming language"]
  author: nikandfor

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"

  analytics:
    google: {}
